#!/usr/bin/env python

import fileinput
import re
import json
import requests
from math import *

for line in fileinput.input():
	calc = json.loads(line)

	m = re.match('^(\d+)\s*([\+\-\*\/])\s*(\d+)$', calc['text'])
	num1 = m.group(1)
	num2 = m.group(3)

	if m.group(2) == '+':
		print(json.dumps({"status": "ok", "text": int(num1) + int(num2)}))
	elif m.group(2) == '-':
		print(json.dumps({"status": "ok", "text": int(num1) - int(num2)}))
	elif m.group(2) == '*':
		print(json.dumps({"status": "ok", "text": int(num1) * int(num2)}))
	elif m.group(2) == '/':
		print(json.dumps({"status": "ok", "text": int(num1) / int(num2)}))
	else:
		print(json.dumps({"status": "error", "text": "error"}))