#!/usr/bin/env node

const sink = require('stream-sink')
const emojis = require('emojilib')

const out = (d) => {process.stdout.write(JSON.stringify(d))}

process.stdin.pipe(sink())
.on('data', (input) => {
	input = JSON.parse(input)
	if (!input.text) return out({status: 'error', text: 'missing keyword'})
	input = input.text.trim().toLowerCase()

	const completions = Object.keys(emojis.lib)
		.filter((name) => name.substr(0, input.length) === input)
		.map((name) => ({
			name: name,
			text: emojis.lib[name].char
		}))

	if (input in emojis.lib) return out({
		status: 'ok', completions,
		text: emojis.lib[input].char
	})
	if (completions.length > 0) return out({status: 'ok', completions})

	out({status: 'error', text: 'couldnt find one'})

})
