#!/usr/bin/env node

const sink = require('stream-sink')

const out = (d) => {process.stdout.write(JSON.stringify(d))}

process.stdin.pipe(sink())
.on('data', (input) => {
	input = JSON.parse(input)
	if (!input.text) return out({status: 'error', text: 'missing text'})

	out({
		status: 'ok',
		text: 'https://twitter.com/intent/tweet?text=' + encodeURIComponent(input.text)
	})

})
